In [1]:
# import the necassery liberaries
import pandas as pd
import numpy as np

In [2]:
def process_company_synthetic (inputFile, outputFile='', seperator=';', minValue=-1, maxValue=-1):
    
    # read data from file
    company = pd.read_csv(inputFile, sep=seperator)
    
    # drop unecessary columns and bad values, including negative numbers and 0
    company = company[['Date','Time','Global_active_power']]
    company.replace(to_replace=r'^\D+[^\.:/-]?\D*[^\.:/-]?\D*$', value=np.NaN, regex=True, inplace=True)
    company.dropna(inplace=True)
    company = company[company['Global_active_power'] > '0']
    
    # drop rows with values bellow the minimum threshold
    if(minValue >= 0):
        company = company[company['Global_active_power'] > str(minValue)]
    
    # drop rows with values over the maximum threshold
    if(maxValue > 0):
        company = company[company['Global_active_power'] < str(maxValue)]
    
    # insert necassary columns 
    company.insert(2,'Latitude', '0')
    company.insert(3,'Longitude', '0')
    company.insert(4,'Size', '0')
    company.insert(5,'Office_or_factory', '0')
    company.insert(6,'Solarpanels', '0')
    company.insert(7,'Heating_type', '0')
    company.insert(8,'Operating_hours', '0')
    
    # write data to file (same file if no outputFile is defined)
    if not outputFile:
        outputFile = inputFile
    company.to_csv(outputFile)
    return company

In [27]:
process_company_synthetic('./real/Company_data_synthetic_generated.csv','./real/company_synthetic_generated_filtered.csv', minValue=50, maxValue=61).head(10)

,Date,Time,Latitude,Longitude,Size,Office_or_factory,Solarpanels,Heating_type,Operating_hours,Global_active_power
2,16/12/2006,17:26:00,0,0,0,0,0,0,0,60.250
5,16/12/2006,17:29:00,0,0,0,0,0,0,0,53.987
6,16/12/2006,17:30:00,0,0,0,0,0,0,0,54.258
7,16/12/2006,17:31:00,0,0,0,0,0,0,0,54.258